# Generated by Django 2.2.7 on 2019-12-01 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='game_name',
            field=models.CharField(default='Dark souls', max_length=200),
            preserve_default=False,
        ),
    ]
