# Generated by Django 2.2.7 on 2019-12-03 00:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0002_review_game_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='notes',
            new_name='reviewers_opinion',
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
