# Generated by Django 3.0 on 2019-12-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0004_auto_20191206_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='video_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
